export const avsGovernanceSmartContractAbi = [
    {
       "type":"function",
       "name":"isOperatorRegistered",
       "inputs":[
          {
             "name":"operator",
             "type":"address",
             "internalType":"address"
          }
       ],
       "outputs":[
          {
             "name":"",
             "type":"bool",
             "internalType":"bool"
          }
       ],
       "stateMutability":"view"
    },
    {
      "type": "function",
      "name": "registerAsOperator",
      "inputs": [
        {
          "name": "_operatorRegistrationParams",
          "type": "tuple",
          "internalType": "struct IAvsGovernance.OperatorRegistrationParams",
          "components": [
            {
              "name": "blsKey",
              "type": "uint256[4]",
              "internalType": "uint256[4]"
            },
            {
              "name": "rewardsReceiver",
              "type": "address",
              "internalType": "address"
            },
            {
              "name": "blsRegistrationSignature",
              "type": "tuple",
              "internalType": "struct BLSAuthLibrary.Signature",
              "components": [
                {
                  "name": "signature",
                  "type": "uint256[2]",
                  "internalType": "uint256[2]"
                }
              ]
            },
            {
              "name": "authToken",
              "type": "bytes",
              "internalType": "bytes"
            }
          ]
        }
      ],
      "outputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "registerOperatorToEigenLayer",
      "inputs": [
        {
          "name": "_eigenSig",
          "type": "tuple",
          "internalType": "struct ISignatureUtilsMixinTypes.SignatureWithSaltAndExpiry",
          "components": [
            {
              "name": "signature",
              "type": "bytes",
              "internalType": "bytes"
            },
            {
              "name": "salt",
              "type": "bytes32",
              "internalType": "bytes32"
            },
            {
              "name": "expiry",
              "type": "uint256",
              "internalType": "uint256"
            }
          ]
        },
        {
          "name": "_authToken",
          "type": "bytes",
          "internalType": "bytes"
        }
      ],
      "outputs": [],
      "stateMutability": "nonpayable"
    },
    {
       "type":"function",
       "name":"unregisterAsOperator",
       "inputs":[
          
       ],
       "outputs":[
          
       ],
       "stateMutability":"nonpayable"
    },
    {
       "type":"function",
       "name":"updateAVSMetadataURI",
       "inputs":[
          {
             "name":"metadataURI",
             "type":"string",
             "internalType":"string"
          }
       ],
       "outputs":[
          
       ],
       "stateMutability":"nonpayable"
    },
    {
       "type":"function",
       "name":"vault",
       "inputs":[
          
       ],
       "outputs":[
          {
             "name":"",
             "type":"address",
             "internalType":"address"
          }
       ],
       "stateMutability":"view"
    },
    {
       "type":"event",
       "name":"FlowPaused",
       "inputs":[
          {
             "name":"_pausableFlow",
             "type":"bytes4",
             "indexed":false,
             "internalType":"bytes4"
          },
          {
             "name":"_pauser",
             "type":"address",
             "indexed":false,
             "internalType":"address"
          }
       ],
       "anonymous":false
    },
    {
       "type":"event",
       "name":"FlowUnpaused",
       "inputs":[
          {
             "name":"_pausableFlowFlag",
             "type":"bytes4",
             "indexed":false,
             "internalType":"bytes4"
          },
          {
             "name":"_unpauser",
             "type":"address",
             "indexed":false,
             "internalType":"address"
          }
       ],
       "anonymous":false
    },
    {
       "type":"event",
       "name":"Initialized",
       "inputs":[
          {
             "name":"version",
             "type":"uint64",
             "indexed":false,
             "internalType":"uint64"
          }
       ],
       "anonymous":false
    },
    {
       "type":"event",
       "name":"MaxEffectiveBalanceSet",
       "inputs":[
          {
             "name":"maxEffectiveBalance",
             "type":"uint256",
             "indexed":false,
             "internalType":"uint256"
          }
       ],
       "anonymous":false
    },
    {
       "type":"event",
       "name":"MinSharesPerStrategySet",
       "inputs":[
          {
             "name":"strategy",
             "type":"address",
             "indexed":false,
             "internalType":"address"
          },
          {
             "name":"minShares",
             "type":"uint256",
             "indexed":false,
             "internalType":"uint256"
          }
       ],
       "anonymous":false
    },
    {
       "type":"event",
       "name":"MinVotingPowerSet",
       "inputs":[
          {
             "name":"minVotingPower",
             "type":"uint256",
             "indexed":false,
             "internalType":"uint256"
          }
       ],
       "anonymous":false
    },
    {
       "type":"event",
       "name":"OperatorRegistered",
       "inputs":[
          {
             "name":"operator",
             "type":"address",
             "indexed":true,
             "internalType":"address"
          },
          {
             "name":"blsKey",
             "type":"uint256[4]",
             "indexed":false,
             "internalType":"uint256[4]"
          }
       ],
       "anonymous":false
    },
    {
       "type":"event",
       "name":"OperatorUnregistered",
       "inputs":[
          {
             "name":"operator",
             "type":"address",
             "indexed":false,
             "internalType":"address"
          }
       ],
       "anonymous":false
    },
    {
       "type":"event",
       "name":"QueuedRewardsReceiverModification",
       "inputs":[
          {
             "name":"operator",
             "type":"address",
             "indexed":false,
             "internalType":"address"
          },
          {
             "name":"receiver",
             "type":"address",
             "indexed":false,
             "internalType":"address"
          },
          {
             "name":"delay",
             "type":"uint256",
             "indexed":false,
             "internalType":"uint256"
          }
       ],
       "anonymous":false
    },
    {
       "type":"event",
       "name":"RoleAdminChanged",
       "inputs":[
          {
             "name":"role",
             "type":"bytes32",
             "indexed":true,
             "internalType":"bytes32"
          },
          {
             "name":"previousAdminRole",
             "type":"bytes32",
             "indexed":true,
             "internalType":"bytes32"
          },
          {
             "name":"newAdminRole",
             "type":"bytes32",
             "indexed":true,
             "internalType":"bytes32"
          }
       ],
       "anonymous":false
    },
    {
       "type":"event",
       "name":"RoleGranted",
       "inputs":[
          {
             "name":"role",
             "type":"bytes32",
             "indexed":true,
             "internalType":"bytes32"
          },
          {
             "name":"account",
             "type":"address",
             "indexed":true,
             "internalType":"address"
          },
          {
             "name":"sender",
             "type":"address",
             "indexed":true,
             "internalType":"address"
          }
       ],
       "anonymous":false
    },
    {
       "type":"event",
       "name":"RoleRevoked",
       "inputs":[
          {
             "name":"role",
             "type":"bytes32",
             "indexed":true,
             "internalType":"bytes32"
          },
          {
             "name":"account",
             "type":"address",
             "indexed":true,
             "internalType":"address"
          },
          {
             "name":"sender",
             "type":"address",
             "indexed":true,
             "internalType":"address"
          }
       ],
       "anonymous":false
    },
    {
       "type":"event",
       "name":"SetAllowlistSigner",
       "inputs":[
          {
             "name":"allowlistSigner",
             "type":"address",
             "indexed":false,
             "internalType":"address"
          }
       ],
       "anonymous":false
    },
    {
       "type":"event",
       "name":"SetAvsGovernanceLogic",
       "inputs":[
          {
             "name":"avsGovernanceLogic",
             "type":"address",
             "indexed":false,
             "internalType":"address"
          }
       ],
       "anonymous":false
    },
    {
       "type":"event",
       "name":"SetAvsGovernanceMultiplierSyncer",
       "inputs":[
          {
             "name":"avsGovernanceMultiplierSyncer",
             "type":"address",
             "indexed":false,
             "internalType":"address"
          }
       ],
       "anonymous":false
    },
    {
       "type":"event",
       "name":"SetAvsGovernanceMultisig",
       "inputs":[
          {
             "name":"newAvsGovernanceMultisig",
             "type":"address",
             "indexed":false,
             "internalType":"address"
          }
       ],
       "anonymous":false
    },
    {
       "type":"event",
       "name":"SetAvsName",
       "inputs":[
          {
             "name":"avsName",
             "type":"string",
             "indexed":false,
             "internalType":"string"
          }
       ],
       "anonymous":false
    },
    {
       "type":"event",
       "name":"SetIsAllowlisted",
       "inputs":[
          {
             "name":"isAllowlisted",
             "type":"bool",
             "indexed":false,
             "internalType":"bool"
          }
       ],
       "anonymous":false
    },
    {
       "type":"event",
       "name":"SetMessageHandler",
       "inputs":[
          {
             "name":"newMessageHandler",
             "type":"address",
             "indexed":false,
             "internalType":"address"
          }
       ],
       "anonymous":false
    },
    {
       "type":"event",
       "name":"SetNumOfOperatorsLimit",
       "inputs":[
          {
             "name":"newLimitOfNumOfOperators",
             "type":"uint256",
             "indexed":false,
             "internalType":"uint256"
          }
       ],
       "anonymous":false
    },
    {
       "type":"event",
       "name":"SetOthenticRegistry",
       "inputs":[
          {
             "name":"othenticRegistry",
             "type":"address",
             "indexed":false,
             "internalType":"address"
          }
       ],
       "anonymous":false
    },
    {
       "type":"event",
       "name":"SetRewardsReceiver",
       "inputs":[
          {
             "name":"operator",
             "type":"address",
             "indexed":false,
             "internalType":"address"
          },
          {
             "name":"receiver",
             "type":"address",
             "indexed":false,
             "internalType":"address"
          }
       ],
       "anonymous":false
    },
    {
       "type":"event",
       "name":"SetRewardsReceiverModificationDelay",
       "inputs":[
          {
             "name":"modificationDelay",
             "type":"uint256",
             "indexed":false,
             "internalType":"uint256"
          }
       ],
       "anonymous":false
    },
    {
       "type":"event",
       "name":"SetStrategyMultiplier",
       "inputs":[
          {
             "name":"strategy",
             "type":"address",
             "indexed":false,
             "internalType":"address"
          },
          {
             "name":"multiplier",
             "type":"uint256",
             "indexed":false,
             "internalType":"uint256"
          }
       ],
       "anonymous":false
    },
    {
       "type":"event",
       "name":"SetSupportedStrategies",
       "inputs":[
          {
             "name":"strategies",
             "type":"address[]",
             "indexed":false,
             "internalType":"address[]"
          }
       ],
       "anonymous":false
    },
    {
       "type":"event",
       "name":"SetToken",
       "inputs":[
          {
             "name":"token",
             "type":"address",
             "indexed":false,
             "internalType":"address"
          }
       ],
       "anonymous":false
    },
    {
       "type":"error",
       "name":"AccessControlBadConfirmation",
       "inputs":[
          
       ]
    },
    {
       "type":"error",
       "name":"AccessControlInvalidMultiplierSyncer",
       "inputs":[
          
       ]
    },
    {
       "type":"error",
       "name":"AccessControlUnauthorizedAccount",
       "inputs":[
          {
             "name":"account",
             "type":"address",
             "internalType":"address"
          },
          {
             "name":"neededRole",
             "type":"bytes32",
             "internalType":"bytes32"
          }
       ]
    },
    {
       "type":"error",
       "name":"AllowlistDisabled",
       "inputs":[
          
       ]
    },
    {
       "type":"error",
       "name":"AllowlistEnabled",
       "inputs":[
          
       ]
    },
    {
       "type":"error",
       "name":"BNAddCallFailed",
       "inputs":[
          
       ]
    },
    {
       "type":"error",
       "name":"BadFTMappingImplementation",
       "inputs":[
          
       ]
    },
    {
       "type":"error",
       "name":"ECDSAInvalidSignature",
       "inputs":[
          
       ]
    },
    {
       "type":"error",
       "name":"ECDSAInvalidSignatureLength",
       "inputs":[
          {
             "name":"length",
             "type":"uint256",
             "internalType":"uint256"
          }
       ]
    },
    {
       "type":"error",
       "name":"ECDSAInvalidSignatureS",
       "inputs":[
          {
             "name":"s",
             "type":"bytes32",
             "internalType":"bytes32"
          }
       ]
    },
    {
       "type":"error",
       "name":"FlowIsCurrentlyPaused",
       "inputs":[
          
       ]
    },
    {
       "type":"error",
       "name":"FlowIsCurrentlyUnpaused",
       "inputs":[
          
       ]
    },
    {
       "type":"error",
       "name":"InvalidAllowlistAuthToken",
       "inputs":[
          
       ]
    },
    {
       "type":"error",
       "name":"InvalidBlsRegistrationSignature",
       "inputs":[
          
       ]
    },
    {
       "type":"error",
       "name":"InvalidFieldElement",
       "inputs":[
          
       ]
    },
    {
       "type":"error",
       "name":"InvalidInitialization",
       "inputs":[
          
       ]
    },
    {
       "type":"error",
       "name":"InvalidMultiplierNotSet",
       "inputs":[
          
       ]
    },
    {
       "type":"error",
       "name":"InvalidRewardsReceiver",
       "inputs":[
          
       ]
    },
    {
       "type":"error",
       "name":"InvalidSlashingRate",
       "inputs":[
          
       ]
    },
    {
       "type":"error",
       "name":"InvalidStrategy",
       "inputs":[
          
       ]
    },
    {
       "type":"error",
       "name":"ModificationDelayNotPassed",
       "inputs":[
          
       ]
    },
    {
       "type":"error",
       "name":"NotInitializing",
       "inputs":[
          
       ]
    },
    {
       "type":"error",
       "name":"NumOfActiveOperatorsIsGreaterThanNumOfOperatorLimit",
       "inputs":[
          {
             "name":"numOfOperatorsLimit",
             "type":"uint256",
             "internalType":"uint256"
          },
          {
             "name":"numOfActiveOperators",
             "type":"uint256",
             "internalType":"uint256"
          }
       ]
    },
    {
       "type":"error",
       "name":"NumOfOperatorsLimitReached",
       "inputs":[
          {
             "name":"numOfOperatorsLimit",
             "type":"uint256",
             "internalType":"uint256"
          }
       ]
    },
    {
       "type":"error",
       "name":"OperatorAlreadyRegistered",
       "inputs":[
          
       ]
    },
    {
       "type":"error",
       "name":"OperatorNotRegistered",
       "inputs":[
          
       ]
    },
    {
       "type":"error",
       "name":"PauseFlowIsAlreadyPaused",
       "inputs":[
          
       ]
    },
    {
       "type":"error",
       "name":"ReentrancyGuardReentrantCall",
       "inputs":[
          
       ]
    },
    {
       "type":"error",
       "name":"Unauthorized",
       "inputs":[
          {
             "name":"message",
             "type":"string",
             "internalType":"string"
          }
       ]
    },
    {
       "type":"error",
       "name":"UnpausingFlowIsAlreadyUnpaused",
       "inputs":[
          
       ]
    }
 ];
